---
output: html_document
mathjax: "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML"
---

## Fishing Mortality, Relative to Overfishing Limits

Analogously to stock status, it will be a higher priority to assess a stock whose fishing mortality represents a larger percentage of its Overfishng Limit (OFL), all other things being equal. Fishing mortality estimates developed by the West Coast Fisheries Observer Program Groundfish Expanded Multiyear Mortality report were averaged over the 2018-2020 period, and then divided by the average OFL (or OFL contribution) for each stock over the same period, to calculate the ratio used to scoring this Factor. Average Acceptable Biological Catches (ABCs) and percentages of ABC attainment are also presented for comparison, but are not used in scoring this Factor.

The scoring of this factor by species are shown in Table 7.

```{r, results = 'asis', echo = FALSE}
library(gt)

mort <- data.frame(matrix(NA, 10, 2))
colnames(mort) <- c("Score", "Stock Harvest Status")

mort[1,]  = c(1, "Negligible fisheries impact on the stock (\\(F \\le 0.10*OFL\\))." )
mort[2,]  = c(2, "Low fisheries impact on the stock (\\(0.10*OFL <  F \\le 0.25*OFL\\)).")
mort[3,]  = c(3, "Moderately low fisheries impact on the stock (\\(0.25*OFL <  F \\le 0.50*OFL\\)).")
mort[4,]  = c(4, "Caution  because the OFL is unknown and \\(F \\le 5 mt.\\)")
mort[5,]  = c(5, "Moderate fisheries impact on the stock (\\(0.50*OFL <  F \\le 0.75*OFL\\)).")
mort[6,]  = c(6, "Caution  because either the F or OFL is unknown and \\(F > 5 mt.\\)")
mort[7,]  = c(7, "Moderately high fisheries impact on the stock (\\(0.75*OFL <  F \\le 0.90*OFL\\)).")
mort[8,]  = c(8, "High fisheries impact, potential overfishing on the stock (\\(0.90*OFL <  F \\le OFL\\)).")
mort[9,]  = c(9, "Mortality slightly above the OFL or the OFL contribution for the stock (\\(OFL <  F \\le 1.1*OFL\\)).")
mort[10,] = c(10, "Mortality well above the OFL or the OFL contribution for the stock (\\(1.1*OFL <  F \\)).")

mort_tbl <- mort %>%
  gt() %>%
  tab_header(
    title = "Table 7: Scores applied based on the percent of the OFL attainment."
  ) %>%
  cols_align(
    align = "left"
  )

mort_tbl

```