---
output: html_document
---

## Ecosystem Importance

Ecosystem importance scores are intended to describe the relative importance of each species to the trophic dynamics of the California Current ecosystem.  We based the ecosystem importance scores on an Ecopath model for the California Current ecosystem [(Koehn et al. 2016)](https://pdf.sciencedirectassets.com/271743/1-s2.0-S0304380016X00130/1-s2.0-S0304380016301909/main.pdf?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEIX%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLWVhc3QtMSJGMEQCIAx%2BFWuZy2ewkBauaLMtbQ8mALL7BfWRGwiMwgnMHKGCAiBDTDisv7rGJtSnLORj0Ii8w3yQ8fKIjY5ZH%2BqkGqNR9yqzBQhNEAUaDDA1OTAwMzU0Njg2NSIMEdx9UO2SrJhEOIVCKpAFJbCbVeypQWgd8%2Bxtd5QTEfv9F9Lhd%2Fhm3Gryz2FbCqUM7VL%2B2VGqgtTzH%2B3MgdOvzGbTkhojmnBOaYlQvG%2FG9wv91b%2BuN9IVm8ApsOkLsFlJU%2BvhXikmEX6z4GdTHQvwKInJ%2Fc1Vqu9EWMpXfuEwRcm5LOXal7K%2FOgHBgRPCHYcji4ktSpzQ%2Fx6rGsycUI5ts617qMKfth8kH230V3%2FAVkMeYsYQbcj%2F%2B9T7hKXy%2Fqn9zjGSgDG5a4zvg%2FPo1ni34Aq09T8IPCrOrufFgkHMih58lkVc%2BiJCqnbI2fXtF7UDhZ2Lme0oiH21LEh5lTEqoJ%2Blg4AyMfPVY1t4yx7KWAaAz%2FCA2ssHDhrldZVwQH%2FkLH7Q6goaC4kg2kL6xSceZov5OYRYto818KZ1h3haO6lH3zxLOvenzJswf%2BP1iKWM9L62d%2BWEJFA9mthkcNQnG59sIg4vCyzQK9o2Fd8BOjEk1Qpzj3lqtm8GirHwIz1r8lvw%2F1his76%2BNt8PV9Uih8UjOPa8Bb1X8KZLW9twgxOD93ncJyleB0o0B7XefBmAogod%2B8NsX1AwbLWUzC2l9VmN5yRzhX0lDd%2BX1Xhu0jzQB1vQ3cVzOvrFeVGILLUlqUrK%2BTfu9NCrObCq4yxLD4Lzm9lH2bQ2gl5BGJsiloN%2FTOfSG2adQWKilJBUlr4wUsnxk2MO8epnnouCkjtU4yElJwds0mZifPRFCUUgSErh5A2iVGZBgVo4Rd6DIOR8KXOrmisSH9qAqBX2HftZ32UXnaU%2BrM%2FpF%2FA8KRV4hX2XnwHkTMJeJcOcIVYTb5yh0OTn4J0DuvF9G7yrVU7otywDkWoVx2Och72bQgM5mAMZ0nAqCHmW82fpbAHriY8wj5WkpwY6sgFp5hGAGzMltjyShx6n1v%2B%2FU3jmPkcl20HmebwA%2FdrAlgeTdmD9UcrfVytRaz%2Fh1aSdPeYoKV5hu3iZ%2FNGAFPpfqDeDXmcri0AhaGkwA61FUDHpnsc4FaBy3GRiV5rp9Sw5rUauZNZMuBhL6sYP%2Bal5OquJdWNFcAbdq8R6ayvU1mrmT6s5g7bEPt3IHOcoFLUZvb9lr6liWFFB5ZacBtJwaOJms0uqiP%2Bf42FY7yiYCcOQ&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20230825T212406Z&X-Amz-SignedHeaders=host&X-Amz-Expires=300&X-Amz-Credential=ASIAQ3PHCVTY6IK5VK5N%2F20230825%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=f7e0284498f44e35a554f9deee67eed26dbc9373c004ed54f5f6e24435a34675&hash=14dabdb60e555b3cf5af3ef05791b32de9bd33e8637524e4c44745217939c83c&host=68042c943591013ac2b2430a89b270f6af2c76d8dfd086a07176afe7c76c2c61&pii=S0304380016301909&tid=spdf-cdc42426-647d-46a7-a40f-483b6d1aab18&sid=3be95f4d2418e3464e8bcef82fb5898b0acagxrqa&type=client&tsoh=d3d3LnNjaWVuY2VkaXJlY3QuY29t&ua=0f10540705590b525254&rr=7fc6e666e9e5c36e&cc=us). Importance scores have top-down and a bottom-up components, which are summed.  First each species was matched to the corresponding functional group from the Ecopath model, and the proportional contribution of each species to the functional group was calculated using the OFL contributions from the Fishing Mortality tab.  

The top-down component represents the importance of each species as a predator of managed or protected species in the California Current ecosystem.  We represent this as an index of the proportion of total consumption in the ecosystem that can be attributed to each species.  The score is the product of several factors; 1) the proportion of the functional group's adult diet consisting of managed or protected species, 2) the functional group's total consumption rate ($QB*B$ defined in Ecopath), and 3) the proportion of the functional group that consists of the species (calculated from the OFL percentages). The product is then divided by the summed total consumption of managed or protected species.  We then re-scale that proportion using all the functional groups in the Ecopath model, not just groundfish, to range from 0 to 10. 

The bottom-up component represents the importance of the species as a prey species to all predators in the ecosystem. We used the proportion of total consumer biomass to represent the contribution of each species.  This index has been used by others to describe the importance of forage species to ecosystem dynamics [(Smith et al. 2011)](https://www.science.org/doi/10.1126/science.1209395) and is referred to as the 'Proportion of species available for consumption'. We calculated the index value for each species in the prioritization, using biomass from the Ecopath model and attributing it to each species using the OFL percentages as we did with the top-down score. Because juvenile life stages of groundfish may be more important prey items than adult, we added apportioned biomass from the four juvenile fish groups in the Ecopath model (juvenile rockfish, juvenile flatfish, juvenile thornyhead, and juvenile roundfish) to each of the relevant species biomasses. The species biomass was divided by the total consumer biomass from the model (all functional groups summed except phytoplankton and detritus).  These percentages were then scaled to the ecosystem by dividing by the most abundant consumer functional group and rescaled to range from 0 to 10.

The ecosystem factor score $e_s$ is calculated as:

$$
e_s = \frac{10*(\text{Top Down}_s + \text{Bottom Up}_s)}{\text{max}(\text{Top Down}_s + \text{Bottom Up}_s)}
$$

The groundfish top-down scores were much higher than the bottom-up scores, illustrating that in general, the groundfish species are, on balance, more important as predators than prey in California Current ecosystem.  For reference, the five highest top-down scores in Ecopath model were calculated for Pacific hake, Pacific spiny dogfish, California sea lions, sablefish, and arrowtooth flounder.  The five highest bottom-up scores at the ecosystem-scale were for benthic infauna, euphausiids, mesopelagics, copepods, and epibenthic invertebrates. Pacific hake was ranked 6th for bottom-up scores.

There were two species that could not be attributed to a functional group from the [Koehn et al., (2016)](https://pdf.sciencedirectassets.com/271743/1-s2.0-S0304380016X00130/1-s2.0-S0304380016301909/main.pdf?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEIX%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLWVhc3QtMSJGMEQCIAx%2BFWuZy2ewkBauaLMtbQ8mALL7BfWRGwiMwgnMHKGCAiBDTDisv7rGJtSnLORj0Ii8w3yQ8fKIjY5ZH%2BqkGqNR9yqzBQhNEAUaDDA1OTAwMzU0Njg2NSIMEdx9UO2SrJhEOIVCKpAFJbCbVeypQWgd8%2Bxtd5QTEfv9F9Lhd%2Fhm3Gryz2FbCqUM7VL%2B2VGqgtTzH%2B3MgdOvzGbTkhojmnBOaYlQvG%2FG9wv91b%2BuN9IVm8ApsOkLsFlJU%2BvhXikmEX6z4GdTHQvwKInJ%2Fc1Vqu9EWMpXfuEwRcm5LOXal7K%2FOgHBgRPCHYcji4ktSpzQ%2Fx6rGsycUI5ts617qMKfth8kH230V3%2FAVkMeYsYQbcj%2F%2B9T7hKXy%2Fqn9zjGSgDG5a4zvg%2FPo1ni34Aq09T8IPCrOrufFgkHMih58lkVc%2BiJCqnbI2fXtF7UDhZ2Lme0oiH21LEh5lTEqoJ%2Blg4AyMfPVY1t4yx7KWAaAz%2FCA2ssHDhrldZVwQH%2FkLH7Q6goaC4kg2kL6xSceZov5OYRYto818KZ1h3haO6lH3zxLOvenzJswf%2BP1iKWM9L62d%2BWEJFA9mthkcNQnG59sIg4vCyzQK9o2Fd8BOjEk1Qpzj3lqtm8GirHwIz1r8lvw%2F1his76%2BNt8PV9Uih8UjOPa8Bb1X8KZLW9twgxOD93ncJyleB0o0B7XefBmAogod%2B8NsX1AwbLWUzC2l9VmN5yRzhX0lDd%2BX1Xhu0jzQB1vQ3cVzOvrFeVGILLUlqUrK%2BTfu9NCrObCq4yxLD4Lzm9lH2bQ2gl5BGJsiloN%2FTOfSG2adQWKilJBUlr4wUsnxk2MO8epnnouCkjtU4yElJwds0mZifPRFCUUgSErh5A2iVGZBgVo4Rd6DIOR8KXOrmisSH9qAqBX2HftZ32UXnaU%2BrM%2FpF%2FA8KRV4hX2XnwHkTMJeJcOcIVYTb5yh0OTn4J0DuvF9G7yrVU7otywDkWoVx2Och72bQgM5mAMZ0nAqCHmW82fpbAHriY8wj5WkpwY6sgFp5hGAGzMltjyShx6n1v%2B%2FU3jmPkcl20HmebwA%2FdrAlgeTdmD9UcrfVytRaz%2Fh1aSdPeYoKV5hu3iZ%2FNGAFPpfqDeDXmcri0AhaGkwA61FUDHpnsc4FaBy3GRiV5rp9Sw5rUauZNZMuBhL6sYP%2Bal5OquJdWNFcAbdq8R6ayvU1mrmT6s5g7bEPt3IHOcoFLUZvb9lr6liWFFB5ZacBtJwaOJms0uqiP%2Bf42FY7yiYCcOQ&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20230825T212655Z&X-Amz-SignedHeaders=host&X-Amz-Expires=300&X-Amz-Credential=ASIAQ3PHCVTY6IK5VK5N%2F20230825%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=5f4cb520a6c0cee72706e637a83cd5a12b514f6f05fcaf00e74c3601109675c9&hash=e9f4381fc305ae0e532b91d04413f2ed8c6e7e71a27b07e0460c98ab0d470572&host=68042c943591013ac2b2430a89b270f6af2c76d8dfd086a07176afe7c76c2c61&pii=S0304380016301909&tid=spdf-3a9d5770-b210-48b7-840a-b3c4b6be98e5&sid=3be95f4d2418e3464e8bcef82fb5898b0acagxrqa&type=client&tsoh=d3d3LnNjaWVuY2VkaXJlY3QuY29t&ua=0f10540705590b055c57&rr=7fc6ea857ee1c36e&cc=us) model: California scorpionfish and Pacific cod.  In the absence of information, we assigned these species the median top down and bottom up scores for all groundfish that were present in the model. The top-down and bottom-up scores were combined by summing the ecosystem-scaled scores and then these scores are re-scaled to range between 0 and 10.